import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormBuilder, FormControl, FormGroup } from '@angular/forms';
import { IReservation } from '../../models/reservation/reservation.interface';
import { DisabledTimeslotService } from '../../services/disabledTimeslot/disabledTimeslot.service';
import { DisabledTimeslot } from '../../models/disabledTimeslot/disabledTimeslot.interface';
import { ReservationFormService } from '../../services/reservation-form/reservation-form.service';
import { ITimeslot } from '../../models/timeslot/timeslot.interface';

@Component({
    selector: 'app-reservation-form',
    templateUrl: './reservation-form.component.html',
    styleUrl: './reservation-form.component.scss',
    standalone: false
})
export class ReservationFormComponent implements OnInit {
  @Input() fieldId!: string;
  @Input() timeslots: ITimeslot[] = [];
  @Input() disabledTimeslots: DisabledTimeslot[] = [];
  @Input() prefillData: IReservation | null = null;

  @Output() reserveTimeslot = new EventEmitter<IReservation>();

  reservationForm!: FormGroup;
  disabledTimeslotIds: string[] = [];
  selectedDate: Date | null = null;
  disabledDates: string[] = [];

  constructor(
    private reservationFormService: ReservationFormService
  ) {}

  ngOnInit(): void {
    this.filterDisabledTimeslots();
    this.computeFullyBookedDates();

    if (this.prefillData) {
      this.selectedDate = new Date(this.prefillData.date);
      this.createForm(this.prefillData);
    } else {
      this.createForm();
    }
  }

  private createForm(reservation?: IReservation): void {
    this.reservationForm = this.reservationFormService.createReservationForm(reservation);
  }

  private filterDisabledTimeslots(): void {
    this.disabledTimeslotIds = this.disabledTimeslots
      .filter(d => d.fieldId === this.fieldId.toString())
      .map(slot => slot.timeslotId);
  }

  resetForm(): void {
    this.reservationForm.reset();
    this.selectedDate = null;
  }

  onDateChange(date: Date): void {
    this.selectedDate = date;
  }

  submitReservation(): void {
    if (this.reservationForm.valid && this.selectedDate) {
      const reservation: IReservation = {
        ...this.reservationForm.value,
        fieldId: this.fieldId,
        date: this.selectedDate.toISOString().split('T')[0],
        confirmationNo: '', // to be filled after payment
        reservationId: '',  // generated by backend
        status: '',         // filled on backend
        createdAt: ''       // filled on backend
      };

      this.reserveTimeslot.emit(reservation);
    }
  }

  // Disable past dates and fully booked dates
  isDateDisabled = (date: Date): boolean => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
  
    const target = new Date(date);
    target.setHours(0, 0, 0, 0);
  
    const formatted = target.toISOString().split('T')[0];
  
    // ❌ Disable past dates
    // ❌ Disable fully booked dates
    return target >= today || this.disabledDates.includes(formatted);
  };
  

  private computeFullyBookedDates(): void {
    const totalSlots = this.timeslots.length;
    const countByDate: Record<string, number> = {};

    this.disabledTimeslots.forEach((entry) => {
      if (entry.fieldId === this.fieldId) {
        countByDate[entry.date] = (countByDate[entry.date] || 0) + 1;
      }
    });

    this.disabledDates = Object.entries(countByDate)
      .filter(([_, count]) => count >= totalSlots)
      .map(([date]) => date);
  }

  // Getters for template
  get reserverName(): FormControl {
    return this.reservationForm.get('reserverName') as FormControl;
  }

  get mobile(): FormControl {
    return this.reservationForm.get('mobile') as FormControl;
  }

  get timeslotId(): FormControl {
    return this.reservationForm.get('timeslotId') as FormControl;
  }

  get paymentMethod(): FormControl {
    return this.reservationForm.get('paymentMethod') as FormControl;
  }
}
